template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: pipeline_test
    steps:
      - name: step_1
        type: Bash
        configuration:
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - echo "step_1 executed"
  - name: pipeline_test2
    steps:
      - name: step_2
        type: Bash
        configuration:
        execution:
          onExecute:
            - echo "step_2 executed""