template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

pipelines:
  - name: Maven_Quickstart
    steps:
      - name: mvn_build_step
        type: Bash
        configuration:
          inputResources:
            - name: mvn_repo
        execution:
          onStart:
             - save_tests $res_mvn_repo_resourcePath/tests