template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  -- name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps: 
            - name: matrix_fan_out_example

        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead     
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    dog                            # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat                           # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead 
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead  
            - animal:    lizard             # - Set 3
              mineral:   lead        

        execution:
          onExecute:
            - echo "I am executing matrix steplet ${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"